In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, Normalizer, StandardScaler
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [2]:
data = pd.read_csv(r'C:\Users\a_del\OneDrive\Desktop\Ironhack-weeks\Unit 1\week3\lab-customer-analysis-round-6\files_for_lab\csv_files\marketing_customer_analysis.csv')

In [3]:
data

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,BU79786,Washington,2763.519279,No,Basic,Bachelor,2/24/11,Employed,F,56274,...,5,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,QZ44356,Arizona,6979.535903,No,Extended,Bachelor,1/31/11,Unemployed,F,0,...,42,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,AI49188,Nevada,12887.431650,No,Premium,Bachelor,2/19/11,Employed,F,48767,...,38,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,WW63253,California,7645.861827,No,Basic,Bachelor,1/20/11,Unemployed,M,0,...,65,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,HB64268,Washington,2813.692575,No,Basic,Bachelor,2/3/11,Employed,M,43836,...,44,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9129,LA72316,California,23405.987980,No,Basic,Bachelor,2/10/11,Employed,M,71941,...,89,0,2,Personal Auto,Personal L1,Offer2,Web,198.234764,Four-Door Car,Medsize
9130,PK87824,California,3096.511217,Yes,Extended,College,2/12/11,Employed,F,21604,...,28,0,1,Corporate Auto,Corporate L3,Offer1,Branch,379.200000,Four-Door Car,Medsize
9131,TD14365,California,8163.890428,No,Extended,Bachelor,2/6/11,Unemployed,M,0,...,37,3,2,Corporate Auto,Corporate L2,Offer1,Branch,790.784983,Four-Door Car,Medsize
9132,UP19263,California,7524.442436,No,Extended,College,2/3/11,Employed,M,21941,...,3,0,3,Personal Auto,Personal L2,Offer3,Branch,691.200000,Four-Door Car,Large
9133,Y167826,California,2611.836866,No,Extended,College,2/14/11,Unemployed,M,0,...,90,0,1,Corporate Auto,Corporate L3,Offer4,Call Center,369.600000,Two-Door Car,Medsize

In [4]:
#One Hot/Label Encoding (categorical)

In [39]:
data1 = data.copy()

In [40]:
data1.select_dtypes("object")

,Customer,State,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Location Code,Marital Status,Policy Type,Policy,Renew Offer Type,Sales Channel,Vehicle Class,Vehicle Size
0,BU79786,Washington,No,Basic,Bachelor,2/24/11,Employed,F,Suburban,Married,Corporate Auto,Corporate L3,Offer1,Agent,Two-Door Car,Medsize
1,QZ44356,Arizona,No,Extended,Bachelor,1/31/11,Unemployed,F,Suburban,Single,Personal Auto,Personal L3,Offer3,Agent,Four-Door Car,Medsize
2,AI49188,Nevada,No,Premium,Bachelor,2/19/11,Employed,F,Suburban,Married,Personal Auto,Personal L3,Offer1,Agent,Two-Door Car,Medsize
3,WW63253,California,No,Basic,Bachelor,1/20/11,Unemployed,M,Suburban,Married,Corporate Auto,Corporate L2,Offer1,Call Center,SUV,Medsize
4,HB64268,Washington,No,Basic,Bachelor,2/3/11,Employed,M,Rural,Single,Personal Auto,Personal L1,Offer1,Agent,Four-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9129,LA72316,California,No,Basic,Bachelor,2/10/11,Employed,M,Urban,Married,Personal Auto,Personal L1,Offer2,Web,Four-Door Car,Medsize
9130,PK87824,California,Yes,Extended,College,2/12/11,Employed,F,Suburban,Divorced,Corporate Auto,Corporate L3,Offer1,Branch,Four-Door Car,Medsize
9131,TD14365,California,No,Extended,Bachelor,2/6/11,Unemployed,M,Suburban,Single,Corporate Auto,Corporate L2,Offer1,Branch,Four-Door Car,Medsize
9132,UP19263,California,No,Extended,College,2/3/11,Employed,M,Suburban,Married,Personal Auto,Personal L2,Offer3,Branch,Four-Door Car,Large
9133,Y167826,California,No,Extended,College,2/14/11,Unemployed,M,Suburban,Single,Corporate Auto,Corporate L3,Offer4,Call Center,Two-Door Car,Medsize

In [41]:
encoder = OneHotEncoder(drop='first')

In [42]:
data1

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,BU79786,Washington,2763.519279,No,Basic,Bachelor,2/24/11,Employed,F,56274,...,5,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,QZ44356,Arizona,6979.535903,No,Extended,Bachelor,1/31/11,Unemployed,F,0,...,42,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,AI49188,Nevada,12887.431650,No,Premium,Bachelor,2/19/11,Employed,F,48767,...,38,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,WW63253,California,7645.861827,No,Basic,Bachelor,1/20/11,Unemployed,M,0,...,65,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,HB64268,Washington,2813.692575,No,Basic,Bachelor,2/3/11,Employed,M,43836,...,44,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9129,LA72316,California,23405.987980,No,Basic,Bachelor,2/10/11,Employed,M,71941,...,89,0,2,Personal Auto,Personal L1,Offer2,Web,198.234764,Four-Door Car,Medsize
9130,PK87824,California,3096.511217,Yes,Extended,College,2/12/11,Employed,F,21604,...,28,0,1,Corporate Auto,Corporate L3,Offer1,Branch,379.200000,Four-Door Car,Medsize
9131,TD14365,California,8163.890428,No,Extended,Bachelor,2/6/11,Unemployed,M,0,...,37,3,2,Corporate Auto,Corporate L2,Offer1,Branch,790.784983,Four-Door Car,Medsize
9132,UP19263,California,7524.442436,No,Extended,College,2/3/11,Employed,M,21941,...,3,0,3,Personal Auto,Personal L2,Offer3,Branch,691.200000,Four-Door Car,Large
9133,Y167826,California,2611.836866,No,Extended,College,2/14/11,Unemployed,M,0,...,90,0,1,Corporate Auto,Corporate L3,Offer4,Call Center,369.600000,Two-Door Car,Medsize

In [43]:
Categorical_data1 = data1.select_dtypes(exclude = ('int64','float64'))

In [69]:
numerical_data1 = data1.select_dtypes('int64','float64')

In [72]:
numerical_data1

,Income,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,Number of Policies
0,56274,69,32,5,0,1
1,0,94,13,42,0,8
2,48767,108,18,38,0,2
3,0,106,18,65,0,7
4,43836,73,12,44,0,1
...,...,...,...,...,...,...
9129,71941,73,18,89,0,2
9130,21604,79,14,28,0,1
9131,0,85,9,37,3,2
9132,21941,96,34,3,0,3
9133,0,77,3,90,0,1

In [44]:
Categorical_data1

,Customer,State,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Location Code,Marital Status,Policy Type,Policy,Renew Offer Type,Sales Channel,Vehicle Class,Vehicle Size
0,BU79786,Washington,No,Basic,Bachelor,2/24/11,Employed,F,Suburban,Married,Corporate Auto,Corporate L3,Offer1,Agent,Two-Door Car,Medsize
1,QZ44356,Arizona,No,Extended,Bachelor,1/31/11,Unemployed,F,Suburban,Single,Personal Auto,Personal L3,Offer3,Agent,Four-Door Car,Medsize
2,AI49188,Nevada,No,Premium,Bachelor,2/19/11,Employed,F,Suburban,Married,Personal Auto,Personal L3,Offer1,Agent,Two-Door Car,Medsize
3,WW63253,California,No,Basic,Bachelor,1/20/11,Unemployed,M,Suburban,Married,Corporate Auto,Corporate L2,Offer1,Call Center,SUV,Medsize
4,HB64268,Washington,No,Basic,Bachelor,2/3/11,Employed,M,Rural,Single,Personal Auto,Personal L1,Offer1,Agent,Four-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9129,LA72316,California,No,Basic,Bachelor,2/10/11,Employed,M,Urban,Married,Personal Auto,Personal L1,Offer2,Web,Four-Door Car,Medsize
9130,PK87824,California,Yes,Extended,College,2/12/11,Employed,F,Suburban,Divorced,Corporate Auto,Corporate L3,Offer1,Branch,Four-Door Car,Medsize
9131,TD14365,California,No,Extended,Bachelor,2/6/11,Unemployed,M,Suburban,Single,Corporate Auto,Corporate L2,Offer1,Branch,Four-Door Car,Medsize
9132,UP19263,California,No,Extended,College,2/3/11,Employed,M,Suburban,Married,Personal Auto,Personal L2,Offer3,Branch,Four-Door Car,Large
9133,Y167826,California,No,Extended,College,2/14/11,Unemployed,M,Suburban,Single,Corporate Auto,Corporate L3,Offer4,Call Center,Two-Door Car,Medsize

In [45]:
encoder.fit(Categorical_data1)

OneHotEncoder(drop='first')

In [46]:
encoder.transform(Categorical_data1).todense()

matrix([[0., 0., 0., ..., 1., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 1., 1., 0.],
        ...,
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 1., 0.]])

In [47]:
encoder.categories_[1][1:]

array(['California', 'Nevada', 'Oregon', 'Washington'], dtype=object)

In [48]:
cols = list(encoder.categories_[0])[1:] + list(encoder.categories_[1])[1:]
cols

['AA11235',
 'AA16582',
 'AA30683',
 'AA34092',
 'AA35519',
 'AA56476',
 'AA69265',
 'AA71604',
 'AA93585',
 'AB13432',
 'AB21519',
 'AB23825',
 'AB26022',
 'AB31813',
 'AB45325',
 'AB60627',
 'AB62982',
 'AB69140',
 'AB72731',
 'AB73565',
 'AB78984',
 'AB96670',
 'AB98823',
 'AC13887',
 'AC22873',
 'AC24378',
 'AC40767',
 'AC42963',
 'AC58002',
 'AC67315',
 'AC73173',
 'AC75391',
 'AC79024',
 'AD12500',
 'AD18174',
 'AD28349',
 'AD28535',
 'AD33653',
 'AD33971',
 'AD38685',
 'AD56037',
 'AD63766',
 'AD71478',
 'AD89594',
 'AD95939',
 'AE23906',
 'AE30506',
 'AE60813',
 'AE62631',
 'AE74442',
 'AE89300',
 'AE90216',
 'AE93522',
 'AE98193',
 'AF10970',
 'AF17671',
 'AF20716',
 'AF36894',
 'AF37776',
 'AF41118',
 'AF47139',
 'AF48816',
 'AF49027',
 'AF49625',
 'AF69537',
 'AF81450',
 'AG22225',
 'AG32304',
 'AG39150',
 'AG45299',
 'AG47947',
 'AG56998',
 'AG58599',
 'AG62087',
 'AG62140',
 'AG85127',
 'AG85615',
 'AH17051',
 'AH22694',
 'AH39293',
 'AH41065',
 'AH41449',
 'AH53588',
 'AH55475',
 'AH58807',
 'AH65907',
 'AH84063',
 'AH89786',
 'AH92481',
 'AH97088',
 'AH99727',
 'AI11191',
 'AI14767',
 'AI16519',
 'AI47152',
 'AI49188',
 'AI49712',
 'AI58313',
 'AI58500',
 'AI61368',
 'AI74959',
 'AI85843',
 'AJ32539',
 'AJ58038',
 'AJ69060',
 'AJ69778',
 'AJ89107',
 'AJ89108',
 'AK11669',
 'AK11719',
 'AK17025',
 'AK44985',
 'AK46006',
 'AK54675',
 'AK59340',
 'AK61491',
 'AK72422',
 'AK90865',
 'AL21967',
 'AL27471',
 'AL35726',
 'AL43475',
 'AL43715',
 'AL46984',
 'AL50693',
 'AL78075',
 'AL95338',
 'AL96740',
 'AM17304',
 'AM26598',
 'AM26717',
 'AM28777',
 'AM29546',
 'AM30008',
 'AM32820',
 'AM34581',
 'AM36670',
 'AM52614',
 'AM53473',
 'AM57175',
 'AM72411',
 'AM79057',
 'AM88377',
 'AM89558',
 'AM92343',
 'AM94127',
 'AM97901',
 'AM99192',
 'AN21193',
 'AN32867',
 'AN36757',
 'AN47199',
 'AN53225',
 'AN57220',
 'AN67558',
 'AN79079',
 'AN80983',
 'AN97123',
 'AO20938',
 'AO40386',
 'AO42003',
 'AO46433',
 'AO74776',
 'AO77635',
 'AO87348',
 'AO98601',
 'AP23850',
 'AP27994',
 'AP32891',
 'AP34711',
 'AP46166',
 'AP47670',
 'AP52126',
 'AP52565',
 'AP56340',
 'AP59947',
 'AP63665',
 'AP65984',
 'AP66226',
 'AP67935',
 'AP89323',
 'AP90638',
 'AP95078',
 'AP98768',
 'AQ11656',
 'AQ25590',
 'AQ30231',
 'AQ34238',
 'AQ46199',
 'AQ51159',
 'AQ51368',
 'AQ52711',
 'AQ70385',
 'AQ70619',
 'AQ91207',
 'AQ94108',
 'AR17553',
 'AR25213',
 'AR40217',
 'AR47849',
 'AR59416',
 'AR61426',
 'AR63478',
 'AR69517',
 'AR75105',
 'AR83514',
 'AR96516',
 'AR99766',
 'AS17174',
 'AS18084',
 'AS26192',
 'AS48176',
 'AS55478',
 'AS55677',
 'AS60178',
 'AS62048',
 'AS77287',
 'AS78838',
 'AS93181',
 'AS97690',
 'AS99827',
 'AT13963',
 'AT18041',
 'AT24793',
 'AT26484',
 'AT29024',
 'AT30076',
 'AT31367',
 'AT33529',
 'AT36002',
 'AT41276',
 'AT49447',
 'AT52647',
 'AT55072',
 'AT62618',
 'AT72574',
 'AT79008',
 'AT84725',
 'AT86990',
 'AT89553',
 'AT93647',
 'AT98182',
 'AU11344',
 'AU13233',
 'AU23837',
 'AU45793',
 'AU46443',
 'AU46604',
 'AU62013',
 'AU71562',
 'AU75025',
 'AU77281',
 'AU91447',
 'AU94279',
 'AU96286',
 'AU98438',
 'AV17528',
 'AV25133',
 'AV49798',
 'AV72430',
 'AV76907',
 'AV93209',
 'AV96010',
 'AW17574',
 'AW18068',
 'AW27717',
 'AW36627',
 'AW48347',
 'AW71157',
 'AW73065',
 'AW77988',
 'AW84946',
 'AW86033',
 'AX10148',
 'AX28231',
 'AX36597',
 'AX38728',
 'AX39008',
 'AX45422',
 'AX56708',
 'AX70794',
 'AX71238',
 'AX71707',
 'AX86150',
 'AX86552',
 'AX99820',
 'AY18433',
 'AY19539',
 'AY26056',
 'AY29281',
 'AY30324',
 'AY35050',
 'AY35539',
 'AY40674',
 'AY43037',
 'AY52869',
 'AY55759',
 'AY59197',
 'AY73718',
 'AY84441',
 'AY88788',
 'AY98473',
 'AY99324',
 'AZ15952',
 'AZ29426',
 'AZ31562',
 'AZ34845',
 'AZ36763',
 'AZ38648',
 'AZ43057',
 'AZ50087',
 'AZ62651',
 'AZ64856',
 'AZ68072',
 'AZ68184',
 'AZ74055',
 'AZ75509',
 'AZ77669',
 'AZ82578',
 'AZ84403',
 'AZ87715',
 'AZ90068',
 'AZ95587',
 'BA17836',
 'BA19651',
 'BA26944',
 'BA38428',
 'BA40043',
 'BA49679',
 'BA51898',
 'BA52133',
 'BA56812',
 'BA66627',
 'BA75404',
 'BA87048',
 'BA87216',
 'BA92673',
 'BA97018',
 'BB10681',
 'BB11622',
 'BB19609',
 'BB21794',
 'BB41401',
 'BB48165',
 'BB65725',
 'BB82067',
 'BC31913',
 'BC34309',
 'BC35753',
 'BC43958',
 'BC47264',
 'BC48076',
 'BC51708',
 'BC52397',
 'BC53363',
 'BC53546',
 'BC62782',
 'BC64697',
 'BC66536',
 'BC66921',
 'BC75105',
 'BC77846',
 'BC85847',
 'BC86800',
 'BC87161',
 'BC87551',
 'BC90645',
 'BC97773',
 'BD12981',
 'BD13927',
 'BD16530',
 'BD35524',
 'BD35676',
 'BD36887',
 'BD42101',
 'BD53342',
 'BD58297',
 'BD66455',
 'BD69478',
 'BD70337',
 'BD77090',
 'BD84823',
 'BD89564',
 'BE10809',
 'BE17305',
 'BE25221',
 'BE31382',
 'BE33446',
 'BE54454',
 'BE55425',
 'BE61743',
 'BE62503',
 'BE65350',
 'BE69929',
 'BE75190',
 'BE78308',
 'BE92692',
 'BF45697',
 'BF54215',
 'BF55854',
 'BF56053',
 'BF69918',
 'BF72793',
 'BG15419',
 'BG19572',
 'BG30513',
 'BG42047',
 'BG44829',
 'BG48083',
 'BG51419',
 'BG55927',
 'BG60187',
 'BG73480',
 'BG74433',
 'BG76355',
 'BG80246',
 'BG84194',
 'BG85305',
 'BG95711',
 'BG96711',
 'BH11344',
 'BH23017',
 'BH28530',
 'BH35016',
 'BH35482',
 'BH36570',
 'BH36973',
 'BH43020',
 'BH43379',
 'BH52611',
 'BH60627',
 'BH61054',
 'BH61137',
 'BH68769',
 'BH86846',
 'BI17208',
 'BI27443',
 'BI33231',
 'BI34286',
 'BI34376',
 'BI38192',
 'BI46495',
 'BI76326',
 'BI81476',
 'BJ13380',
 'BJ18904',
 'BJ22117',
 'BJ26599',
 'BJ53923',
 'BJ58596',
 'BJ65040',
 'BJ82316',
 'BK15048',
 'BK21146',
 'BK43823',
 'BK47926',
 'BK57087',
 'BK59444',
 'BK61065',
 'BK73302',
 'BK76107',
 'BK76340',
 'BK83393',
 'BK85520',
 'BL12371',
 'BL13393',
 'BL29046',
 'BL29240',
 'BL42392',
 'BL44708',
 'BL44722',
 'BL54814',
 'BL55947',
 'BL66157',
 'BL79888',
 'BL89983',
 'BL90769',
 'BL93527',
 'BL93659',
 'BM15160',
 'BM16805',
 'BM21532',
 'BM27144',
 'BM28359',
 'BM30720',
 'BM31989',
 'BM39234',
 'BM45823',
 'BM46418',
 'BM53580',
 'BM55732',
 'BM66931',
 'BM69081',
 'BM69818',
 'BM70908',
 'BM71358',
 'BM83544',
 'BM92346',
 'BN13780',
 'BN14307',
 'BN38134',
 'BN45584',
 'BN46866',
 'BN62219',
 'BN74259',
 'BN74268',
 'BN77676',
 'BN80677',
 'BN83547',
 'BN87372',
 'BN89470',
 'BN90616',
 'BN91755',
 'BO15959',
 'BO21461',
 'BO42776',
 'BO46265',
 'BO58202',
 'BO81145',
 'BO87401',
 'BO92934',
 'BO94261',
 'BP23267',
 'BP25150',
 'BP28492',
 'BP34620',
 'BP35803',
 'BP49831',
 'BP53979',
 'BP54465',
 'BP69529',
 'BP74289',
 'BP83941',
 'BP90016',
 'BP92643',
 'BQ12347',
 'BQ15946',
 'BQ20851',
 'BQ28323',
 'BQ32117',
 'BQ41371',
 'BQ51587',
 'BQ51616',
 'BQ60673',
 'BQ88033',
 'BQ94892',
 'BQ94931',
 'BQ99053',
 'BR13613',
 'BR22486',
 'BR23201',
 'BR24590',
 'BR28896',
 'BR39076',
 'BR40272',
 'BR44176',
 'BR50492',
 'BR69566',
 'BR76202',
 'BR77413',
 'BR99015',
 'BS13062',
 'BS13111',
 'BS26376',
 'BS29584',
 'BS34332',
 'BS53322',
 'BS77946',
 'BS83666',
 'BS87947',
 'BS90503',
 'BS91566',
 'BS91742',
 'BS94221',
 'BS95225',
 'BS96517',
 'BT20606',
 'BT30554',
 'BT49333',
 'BT57285',
 'BT61680',
 'BT68954',
 'BT76268',
 'BT78461',
 'BT78503',
 'BU14748',
 'BU15334',
 'BU16704',
 'BU17847',
 'BU27331',
 'BU41599',
 'BU44523',
 'BU53191',
 'BU59722',
 'BU61331',
 'BU70181',
 'BU71528',
 'BU72276',
 'BU72633',
 'BU79786',
 'BU81591',
 'BV12771',
 'BV16459',
 'BV22194',
 'BV25135',
 'BV27017',
 'BV33510',
 'BV35683',
 'BV36386',
 'BV53716',
 'BV55014',
 'BV55733',
 'BV57364',
 'BV63942',
 'BV69462',
 'BV79904',
 'BV80674',
 'BV86143',
 'BV91898',
 'BV98316',
 'BW25236',
 'BW43011',
 'BW46202',
 'BW51534',
 'BW52697',
 'BW63560',
 'BW65176',
 'BW76745',
 'BW79345',
 'BW80872',
 'BW88060',
 'BW94308',
 'BX20227',
 'BX20846',
 'BX24569',
 'BX35013',
 'BX45636',
 'BX51438',
 'BX70848',
 'BX88206',
 'BX88330',
 'BX94438',
 'BY22068',
 'BY23642',
 'BY54111',
 'BY59578',
 'BY62906',
 'BY75330',
 'BY78730',
 'BY84257',
 'BY88565',
 'BY88757',
 'BZ12077',
 'BZ33435',
 'BZ36030',
 'BZ44726',
 'BZ47770',
 'BZ50261',
 'BZ65376',
 'BZ71120',
 'BZ81849',
 'BZ85280',
 'BZ85306',
 'BZ92811',
 'CA14631',
 'CA22248',
 'CA29908',
 'CA45756',
 'CA47176',
 'CA52541',
 'CA54112',
 'CA55066',
 'CA56041',
 'CA58346',
 'CA62597',
 'CA70404',
 'CA79988',
 'CA86085',
 'CA96230',
 'CA96568',
 'CB15842',
 'CB17191',
 'CB44654',
 'CB52667',
 'CB58476',
 'CB59349',
 'CB61335',
 'CB62406',
 'CB64729',
 'CB77819',
 'CB78049',
 'CB95310',
 'CB96381',
 'CC15295',
 'CC16034',
 'CC30924',
 'CC31456',
 'CC43119',
 'CC46747',
 'CC85895',
 'CC88237',
 'CC91503',
 'CC92362',
 'CC93587',
 'CC94413',
 'CD14267',
 'CD26907',
 'CD27895',
 'CD38665',
 'CD45044',
 'CD48033',
 'CD55111',
 'CD56261',
 'CD68182',
 'CD71502',
 'CD71877',
 'CD76093',
 'CD86811',
 'CD88896',
 'CD95333',
 'CE10235',
 'CE11308',
 'CE11667',
 'CE12380',
 'CE16324',
 'CE17166',
 'CE17855',
 'CE21829',
 'CE41738',
 'CE46475',
 'CE56187',
 'CE68841',
 'CE69971',
 'CE71123',
 'CE72177',
 'CE75354',
 'CE78778',
 'CE92675',
 'CE94751',
 'CF15086',
 'CF15252',
 'CF15558',
 'CF26052',
 'CF26207',
 'CF27806',
 'CF40646',
 'CF41619',
 'CF44171',
 'CF46699',
 'CF50291',
 'CF57022',
 'CF62430',
 'CF62992',
 'CF73234',
 'CF85061',
 'CF95802',
 'CG13512',
 'CG15505',
 'CG33085',
 'CG36206',
 'CG39505',
 'CG43444',
 'CG60089',
 'CG69038',
 'CG90504',
 'CG92708',
 'CG94611',
 'CH20044',
 'CH38655',
 'CH50339',
 'CH50584',
 'CH73843',
 'CH76379',
 'CH78309',
 'CH81088',
 'CH85057',
 'CH85444',
 'CH95772',
 'CH96412',
 'CH97539',
 'CH97666',
 'CI19819',
 'CI24326',
 'CI27304',
 'CI30899',
 'CI38171',
 'CI38330',
 'CI47242',
 'CI51999',
 'CI57475',
 'CI60365',
 'CI68869',
 'CI95726',
 'CI99444',
 'CJ15590',
 'CJ29883',
 'CJ31839',
 'CJ35075',
 'CJ46674',
 'CJ51511',
 'CJ59481',
 'CJ63667',
 'CJ64468',
 'CJ72056',
 'CJ78727',
 'CJ78860',
 'CJ81391',
 'CJ81799',
 'CJ97736',
 'CK14803',
 'CK15380',
 'CK19789',
 'CK24264',
 'CK29372',
 'CK31454',
 'CK35310',
 'CK36026',
 'CK39096',
 'CK40732',
 'CK74127',
 'CK85904',
 'CL10476',
 'CL37990',
 'CL38124',
 'CL38926',
 'CL52383',
 'CL70684',
 'CL73599',
 'CL79250',
 'CL97519',
 'CM38959',
 'CM42637',
 'CM48429',
 'CM52565',
 'CM55703',
 'CM59084',
 'CM61827',
 'CM66204',
 'CM73149',
 'CM78608',
 'CM84035',
 'CM88932',
 'CM94209',
 'CM94425',
 'CM95716',
 'CN13435',
 'CN16311',
 'CN17219',
 'CN19138',
 'CN22369',
 'CN23147',
 'CN24514',
 'CN29830',
 'CN30964',
 'CN31328',
 'CN49086',
 'CN53343',
 'CN63432',
 'CN90378',
 'CN91738',
 'CO12132',
 'CO15448',
 'CO16841',
 'CO19402',
 'CO23919',
 'CO25601',
 'CO44221',
 'CO44659',
 'CO53249',
 'CO53758',
 'CO56168',
 'CO68055',
 'CO71128',
 'CO71312',
 'CO75086',
 'CO91673',
 'CP19929',
 'CP27565',
 'CP28581',
 'CP30637',
 'CP32818',
 'CP38401',
 'CP47989',
 'CP66511',
 'CP67787',
 'CP74755',
 'CP76842',
 'CP85232',
 'CP87192',
 'CP92616',
 'CP93345',
 'CP98451',
 'CP99334',
 'CQ15251',
 'CQ19667',
 'CQ21583',
 'CQ57225',
 'CQ59706',
 'CQ72935',
 'CQ75652',
 'CQ76030',
 'CQ76876',
 'CQ78705',
 'CQ80529',
 'CQ81839',
 'CR12479',
 'CR20811',
 'CR33417',
 'CR37971',
 'CR40615',
 'CR41258',
 'CR48975',
 'CR56473',
 'CR57148',
 'CR59224',
 'CR76145',
 'CR83581',
 'CR85257',
 'CR86548',
 'CR88883',
 'CR92272',
 'CR92802',
 'CR99369',
 'CS15289',
 'CS26667',
 'CS29328',
 'CS30372',
 'CS30775',
 'CS32416',
 'CS35098',
 'CS51928',
 'CS55808',
 'CS70768',
 'CS84396',
 'CS93971',
 'CT11176',
 'CT18212',
 'CT41158',
 'CT47738',
 'CT50487',
 'CT51200',
 'CT53265',
 'CT62892',
 'CT74097',
 'CT83377',
 'CT84535',
 'CT86614',
 'CT88432',
 'CT96082',
 'CU10179',
 'CU13711',
 'CU19735',
 'CU26127',
 'CU36986',
 'CU69816',
 'CU84967',
 'CV13878',
 'CV24005',
 'CV29889',
 'CV31235',
 'CV35709',
 'CV40610',
 'CV44550',
 'CV48634',
 'CV49750',
 'CV57391',
 'CV63337',
 'CV64725',
 'CV70978',
 'CV72453',
 'CV75841',
 'CV78865',
 'CV86445',
 'CV90092',
 'CV95479',
 'CW12066',
 'CW13886',
 'CW15758',
 'CW16221',
 'CW27031',
 'CW35098',
 'CW38361',
 'CW49887',
 'CW57351',
 'CW57656',
 'CW63533',
 'CW77053',
 'CW80905',
 'CW82151',
 'CW85845',
 'CW92156',
 'CW98743',
 'CW98845',
 'CX12134',
 'CX18273',
 'CX20455',
 'CX22458',
 'CX34236',
 'CX58204',
 'CX65318',
 ...]

In [52]:
from sklearn.preprocessing import LabelEncoder

In [53]:
encoder = LabelEncoder()

In [54]:
encoded_data = Categorical_data1.copy()

In [55]:
for col in Categorical_data1.columns:
    encoded_data[col] = encoder.fit_transform(Categorical_data1[col])

In [56]:
for col in Categorical_data1.columns:
    data1[col] = encoded_data[col]

In [57]:
data1_dense = data1.values

In [63]:
data1 = data1.drop(Categorical_data1, axis=1)
data1

,Customer Lifetime Value,Income,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Total Claim Amount
0,2763.519279,56274,69,32,5,0,1,384.811147
1,6979.535903,0,94,13,42,0,8,1131.464935
2,12887.431650,48767,108,18,38,0,2,566.472247
3,7645.861827,0,106,18,65,0,7,529.881344
4,2813.692575,43836,73,12,44,0,1,138.130879
...,...,...,...,...,...,...,...,...
9129,23405.987980,71941,73,18,89,0,2,198.234764
9130,3096.511217,21604,79,14,28,0,1,379.200000
9131,8163.890428,0,85,9,37,3,2,790.784983
9132,7524.442436,21941,96,34,3,0,3,691.200000
9133,2611.836866,0,77,3,90,0,1,369.600000

In [64]:
data2 = data.copy()

In [66]:
data2 = pd.get_dummies(Categorical_data1, drop_first=True)

In [67]:
data2 = pd.get_dummies(data2, drop_first=True)
data2

,Customer_AA11235,Customer_AA16582,Customer_AA30683,Customer_AA34092,Customer_AA35519,Customer_AA56476,Customer_AA69265,Customer_AA71604,Customer_AA93585,Customer_AB13432,...,Sales Channel_Branch,Sales Channel_Call Center,Sales Channel_Web,Vehicle Class_Luxury Car,Vehicle Class_Luxury SUV,Vehicle Class_SUV,Vehicle Class_Sports Car,Vehicle Class_Two-Door Car,Vehicle Size_Medsize,Vehicle Size_Small
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
3,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9129,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
9130,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
9131,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
9132,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
9133,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,1,0

In [ ]:
#Concat DataFrames

In [70]:
concatenated_data = pd.concat([numerical_data1, encoded_data], axis=1)

In [74]:
X = data1.drop(["Customer Lifetime Value"], axis=1)
y = data["Customer Lifetime Value"]

In [75]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [76]:
y_train

434      5015.009472
4641     5149.301306
4952     4904.894731
1489     8510.525936
812      3278.531880
            ...
5734     7334.328083
5191     5498.940679
5390     8992.779137
860     14635.451580
7270     3349.639274
Name: Customer Lifetime Value, Length: 6393, dtype: float64

In [77]:
scaler = StandardScaler()

In [78]:
scaler.fit(X_train)

StandardScaler()

In [79]:
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [80]:
lm = LinearRegression()

In [81]:
lm.fit(X_train_scaled, y_train)

LinearRegression()

In [82]:
predictions = lm.predict(X_test_scaled)

In [83]:
rmse = mean_squared_error(y_test, predictions, squared=False) # or mse with squared=True
mae = mean_absolute_error(y_test, predictions)
print("R2_score:", round(r2_score(y_test, predictions), 2)) 
print("RMSE:", rmse)
print("MAE:", mae)

R2_score: 0.16
RMSE: 6627.469720048554
MAE: 4039.8522758737386